//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.GrantPrimeV_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrimeGrantEntities : DbContext
    {
        public PrimeGrantEntities()
            : base("name=PrimeGrantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Role> tbl_Role { get; set; }
        public virtual DbSet<tbl_town> tbl_town { get; set; }
        public virtual DbSet<tbl_userprofile> tbl_userprofile { get; set; }
        public virtual DbSet<tbl_AgeGrade> tbl_AgeGrade { get; set; }
        public virtual DbSet<tbl_Applicant> tbl_Applicant { get; set; }
        public virtual DbSet<tbl_ApplicantUploads> tbl_ApplicantUploads { get; set; }
        public virtual DbSet<tbl_Approve> tbl_Approve { get; set; }
        public virtual DbSet<tbl_Committee> tbl_Committee { get; set; }
        public virtual DbSet<tbl_country> tbl_country { get; set; }
        public virtual DbSet<tbl_customer> tbl_customer { get; set; }
        public virtual DbSet<tbl_Disburse> tbl_Disburse { get; set; }
        public virtual DbSet<tbl_Rejection> tbl_Rejection { get; set; }
        public virtual DbSet<tbl_state> tbl_state { get; set; }
    }
}
