//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.GrantPrimeV_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Role
    {
        public int role_id { get; set; }
        public string role_name { get; set; }
        public string roledesc { get; set; }
        public int? access_days { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public int? isoperation { get; set; }
        public int? reqLimit { get; set; }
        public int? status { get; set; }
        public string authid { get; set; }
        public string userid { get; set; }
        public bool canauth { get; set; }
        public int? role_level { get; set; }
        public bool Commitee { get; set; }
    }
}
