//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.GrantPrimeV_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AgeGrade
    {
        public int id { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public Nullable<long> applicant_Id { get; set; }
        public string BVN { get; set; }
        public string AuthId { get; set; }
        public Nullable<int> NoOfEmployee { get; set; }
        public Nullable<int> T1835 { get; set; }
        public Nullable<int> T3645 { get; set; }
        public Nullable<int> T46andabove { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> status { get; set; }
        public string userid { get; set; }
    }
}
