//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.GrantPrimeV_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_userprofile
    {
        public int id { get; set; }
        public string Userid { get; set; }
        public string userpassword { get; set; }
        public string fullname { get; set; }
        public string deptcode { get; set; }
        public int? Role_id { get; set; }
        public string ipaddress { get; set; }
        public string loginstatus { get; set; }
        public int? Authoriser { get; set; }
        public string branchcode { get; set; }
        public string Staff_status { get; set; }
        public string PostGL_Acctno { get; set; }
        public Nullable<System.DateTime> passchange_date { get; set; }
        public Nullable<System.DateTime> Next_Passchange_date { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public Nullable<long> SScode { get; set; }
        public Nullable<int> sessionid { get; set; }
        public string Computername { get; set; }
        public string machaddress { get; set; }
        public Nullable<int> lockcount { get; set; }
        public string ReportLevel { get; set; }
        public string AuthUserid { get; set; }
        public string PostUserId { get; set; }
        public string email { get; set; }
        public string phoneno { get; set; }
        public int? Status { get; set; }
        public string authid { get; set; }
        public Nullable<int> smsalert { get; set; }
        public Nullable<int> emailalert { get; set; }
        public Nullable<int> offlinealert { get; set; }
        public string authorisedby { get; set; }
        public Nullable<int> enforce_pwd { get; set; }
        public Nullable<int> excemptlock { get; set; }
        public Nullable<int> statement { get; set; }
        public Nullable<int> remotelogin { get; set; }
        public Nullable<decimal> targetamt { get; set; }
        public int? logincount { get; set; }
        public int? multilogin { get; set; }
        public int? SBU { get; set; }
        public int? reportflag { get; set; }
        public string ConfirmPassword { get; set; }
        public string PasswordResetCode { get; set; }
        public bool? IsEmailVerified { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
    }
}
