//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.GrantPrimeV_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ApplicantUploads
    {
        public long Upload_Id { get; set; }
        public Nullable<long> Applicant_Id { get; set; }
        public string phone { get; set; }
        public string BVN { get; set; }
        public Nullable<System.DateTime> LastTaxPayDate { get; set; }
        public byte[] LstTaxDatePayEvidnce { get; set; }
        public string LstTaxDateEvidnceType { get; set; }
        public string BusnRegNum { get; set; }
        public byte[] BusnRegNumEvdnce { get; set; }
        public string BusnRegNumEvidnceType { get; set; }
        public Nullable<decimal> Lst3YrAvrgeAnnualBusnTOver { get; set; }
        public byte[] Lst3YrAvrgeAnnualBusnTOverEvdnce { get; set; }
        public string Lst3YrAvrgeAnnualBusnTOverEvdnceType { get; set; }
        public string ApplicantPassportName { get; set; }
        public byte[] ApplicantPassport { get; set; }
        public string ApplicantPassportType { get; set; }
        public byte[] ApplicantSign { get; set; }
        public string ApplicantSignType { get; set; }
        public string EvidnceOfLoanOrCreditGrantName { get; set; }
        public byte[] EvidnceOfLoanOrCreditGrant { get; set; }
        public string EvidnceOfLoanOrCreditGrantType { get; set; }
        public string EvidnceOfOpertnExp4pst3mnthName { get; set; }
        public byte[] EvidnceOfOpertnExp4pst3mnth { get; set; }
        public string EvidnceOfOpertnExp4pst3mnthType { get; set; }
        public string EvidnceOfOCorpOrAssocMemberName { get; set; }
        public byte[] EvidnceOfOCorpOrAssocMember { get; set; }
        public string EvidnceOfOCorpOrAssocMemberType { get; set; }
        public string EnumeratorName { get; set; }
        public byte[] EnumeratorSign { get; set; }
        public string EnumeratorSignType { get; set; }
        public string DL1TeamLeadComment { get; set; }
        public byte[] DL1teamLeadSignWDate { get; set; }
        public string DL1teamLeadSignType { get; set; }
        public Nullable<decimal> DL1teamLeadApprovAmnt { get; set; }
        public string DL2TeamLeadComment { get; set; }
        public byte[] DL2teamLeadSign { get; set; }
        public string DL2teamLeadSignType { get; set; }
        public Nullable<decimal> DL2teamLeadApprovAmnt { get; set; }
        public string DL3TeamLeadComment { get; set; }
        public byte[] DL3teamLeadSignWdDate { get; set; }
        public string DL3teamLeadSignType { get; set; }
        public Nullable<decimal> DL3teamLeadApprovAmnt { get; set; }
        public string StateCareCordinatorComment { get; set; }
        public byte[] StateCareCordinatorSign { get; set; }
        public string StateCareCordinatorSignType { get; set; }
        public Nullable<decimal> StateCareCordinatorApprovAmnt { get; set; }
    }
}
