//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.GrantPrimeV_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_state
    {
        public string StateCode { get; set; }
        public string StateName { get; set; }
        public string Statemne { get; set; }
        public string CountryCode { get; set; }
        public string Capital { get; set; }
        public int? Status { get; set; }
        public string Region { get; set; }
        public string userid { get; set; }
        public string authid { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
