//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.GrantPrimeV_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_country
    {
        public string CountryCode { get; set; }
        public string CountryName { get; set; }
        public string CountryMne { get; set; }
        public Nullable<int> Status { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyMne { get; set; }
        public string userid { get; set; }
        public string authid { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
    }
}
