//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web.GrantPrimeV_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Applicant
    {
        public long applicant_Id { get; set; }
        public Nullable<long> Upload_Id { get; set; }
        public string SurName { get; set; }
        public string FirstName { get; set; }
        public string Middlename { get; set; }
        public string BusinessName { get; set; }
        public string gender { get; set; }
        public string StateOfOrigin { get; set; }
        public string LGA { get; set; }
        public string ResidAddress { get; set; }
        public string Position { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string PersonalTaxRegNo { get; set; }
        public string BusinessSector { get; set; }
        public string BusinessType { get; set; }
        public string BusinessAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string BusinesPhoneNo { get; set; }
        public string BusinesEmail { get; set; }
        public string BusinesWebsite { get; set; }
        public string BusinesTaxRegNo { get; set; }
        public Nullable<System.DateTime> LastTaxPayDate { get; set; }
        public Nullable<System.DateTime> BusinesStartDate { get; set; }
        public Nullable<int> NoOfYrInOperation { get; set; }
        public Nullable<int> NOofEmployee { get; set; }
        public Nullable<int> NOofFemale { get; set; }
        public Nullable<int> NOofMale { get; set; }
        public string AgeGrade { get; set; }
        public Nullable<decimal> EstimValOfBusTurnoverXLB { get; set; }
        public string BankName { get; set; }
        public string AcctNo { get; set; }
        public string BVN { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string AnyRunningLoanPriorToCovid { get; set; }
        public Nullable<decimal> TotalOutstandVolumeOfLoan { get; set; }
        public string HowOftenWereYouPaying { get; set; }
        public Nullable<decimal> HowMuchWereyouPaying { get; set; }
        public string DidYourRepaymentChange { get; set; }
        public Nullable<decimal> RepaymntChangeToHowMuch { get; set; }
        public string findItDiffToMeetPaymentOblig { get; set; }
        public string BusinImpactByCovid { get; set; }
        public string BusiNegImpactByCovid { get; set; }
        public string specifyOther { get; set; }
        public string PlanningToLayOffEmployeeDueToNeg { get; set; }
        public string DidYouLayOffEmployee { get; set; }
        public string NoOffEmployeeLayOff { get; set; }
        public string DidBusContDuringCovidCrisis { get; set; }
        public string WhtToolCudVeMadeItPosib { get; set; }
        public string WhtToolCudVeMadeBusMoreEffnt { get; set; }
        public string EmployeeAbleToWrkFrmHom { get; set; }
        public string WhtToolCudVeReqToMakeItPosib { get; set; }
        public Nullable<int> GrantTypeReqFor { get; set; }
        public string fullname { get; set; }
        public string Declaration { get; set; }
        public string AllSectnOfFormFilled { get; set; }
        public string IsBusinessCertAttach { get; set; }
        public string IsEvidOfTaxPaymentAttach { get; set; }
        public string IsEvOf1YrTOverAttachOrVerifid { get; set; }
        public string VeBnkDetailProvided { get; set; }
        public string IsImpactOfCovidOnBusnVrfd { get; set; }
        public string GrantyTpe { get; set; }
        public Nullable<decimal> CreditGrantAmount { get; set; }
        public Nullable<decimal> OperatnGrantAmount { get; set; }
        public Nullable<decimal> ITEnhanceGrantAmount { get; set; }
        public string approveComment { get; set; }
        public string rejectComment { get; set; }
        public string authId { get; set; }
        public string userId { get; set; }
        public Nullable<int> ApprovalLevel { get; set; }
        public Nullable<int> rejected { get; set; }
        public Nullable<int> Approved { get; set; }
        public string ApprovedBy { get; set; }
        public string rejectedBy { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> ReworkStatus { get; set; }
        public Nullable<decimal> amountApprove { get; set; }
        public Nullable<int> DisburseType { get; set; }
        public Nullable<decimal> amntDisbursed { get; set; }
        public Nullable<decimal> disbursedBalance { get; set; }
        public Nullable<decimal> AmntDue { get; set; }
        public Nullable<int> NoOftranchDisb { get; set; }
        public Nullable<int> TotalNoOfTranDisb { get; set; }
        public string freguency { get; set; }
    }
}
